app/models.py
from . import db
from datetime import datetime
from sqlalchemy_utils.types.phone_number import PhoneNumberType

class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = name = db.Column(db.String(64))
    email = db.Column(db.String(64), index=True)
    phone_number = db.Column(PhoneNumberType(region='RU', max_length=20))
    claims = db.relationship('Claim', backref='author', lazy='dynamic', cascade='all, delete-orphan')
    
    def __repr__(self):
        return '<User %r>' % self.email
    
class Claim(db.Model):
    __tablename__ = 'claims'
    id = db.Column(db.Integer, primary_key=True)
    fabula = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, user):
        self.user_id = user.id

    def __repr__(self):
        return '<Claim %r>' % self.id

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, Regexp
from wtforms_alchemy import PhoneNumberField

class ClaimEditForm(FlaskForm):
    name = StringField('', validators=[Length(0, 64), 
                       Regexp(r'^[А-яа-яA-Za-z]+$', 0, 
                       'Имя должно содержать только одно слово на кириллице либо латинице')], 
                       render_kw={'placeholder': 'Ваше имя'})
    email = StringField('', validators=[DataRequired(), Length(1, 64),
                        Email(message='Формат email не соответствует установленным правилам')], 
                        render_kw={'placeholder': 'Email'})
    phone_number = PhoneNumberField('', validators=[DataRequired()], region='RU', 
                                    render_kw={'placeholder': '+7 (xxx) xxx-xx-xx (вводите цифры без пробелов)'})
    location = StringField('', validators=[Length(0, 64)], 
                           render_kw={'placeholder': 'Город, село (прочее)'})
    fabula = TextAreaField('', validators=[DataRequired()], 
                           render_kw={'placeholder': 'Введите текст здесь'})
    submit = SubmitField('Отправить заявку')

app/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from config import config
import telebot

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
bot = telebot.TeleBot(os.environ.get('TELEBOT'))

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    mail.init_app(app)
        
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)    
    
    return app

app/main/__init__.py
import os
from flask import Blueprint

main = Blueprint('main', __name__)

from app.main import views, errors

app/main/views.py
import os, re
from flask import render_template, request, redirect, url_for, flash
from . import main
from .. import db
from .. models import User, Claim
from . forms import ClaimEditForm
from .. email import send_email
from .. telebot import send_message

@main.route('/')
def index():    
    return render_template('index.html')

@main.route('/email', methods=['GET', 'POST'])
def get_email():
    if request.method == 'POST' and request.form.get('email') != '':
        email = request.form.get('email')
        user = User.query.filter_by(email=email).first()
        if not user:
            user = User(email=email)
            db.session.add(user)
            db.session.commit()
            message = f'Специалист свяжется с Вами по адресу {user.email}!'
            send_email(os.environ.get('APP_ADMIN'), f'Обращение без заявки от клиента {user.email}', 'mail/email_only_admin', user=user)
            send_email(user.email, f'Ответ специалиста придет на {user.email} ', 'mail/email_only_user', user=user)
        else:
            message = f'Мы рады снова видеть Вас {user.email}! Специалист свяжется с Вами!'
            send_email(os.environ.get('APP_ADMIN'), f'Обращение без заявки от клиента {user.email}', 'mail/email_only_admin', user=user)
            send_email(user.email, f'Ответ специалиста придет на {user.email} ', 'mail/email_only_user', user=user)
            return render_template('index.html', repeat=message)
        return render_template('index.html', success=message)
    return redirect(url_for('main.index'))

@main.route('/claim', methods=['GET', 'POST'])
def claim_form():
    form = ClaimEditForm()
    user = User()
    if form.validate_on_submit():
        user = User(name=form.name.data,
                    email = form.email.data,
                    phone_number = form.phone_number.data
                    )
        db.session.add(user)
        db.session.flush()
        claim = Claim(user)
        claim.fabula = form.fabula.data
        db.session.add(claim)
        db.session.commit()
        send_email(os.environ.get('APP_ADMIN'), f'Заявка № {claim.id}', 'mail/send_admin', user=user, claim=claim)
        send_email(user.email, f'Номер Вашей заявки (заявка № {claim.id})', 'mail/send_user', user=user, claim=claim)
        if isinstance(form.name.data, str) and form.name.data[-1] in ['а', 'a']:
            message = f'Уважаемая {form.name.data}! Заявка принята. Ответ поступит на {form.email.data} или {form.phone_number.data}'
        else:
            message = f'Уважаемый {form.name.data}! Заявка принята. Ответ поступит на {form.email.data} или {form.phone_number.data}'        
        return render_template('claimform.html', form=form, success=message)
    return render_template('claimform.html', form=form)


@main.route('/process', methods=['POST'])
def process():
    if request.method == 'POST':
        name = request.json.get('message', 'Сообщение отсутствует').get('chat', 'Сведения о чате отсутствуют').get('last_name', 'клиент')
        question = request.json.get('message', 'Сообщение отсутствует').get('text', 'Сообщение отсутствует')
        chat_id = request.json.get('message', 'Сообщение отсутствует').get('chat', 'Сведения о чате отсутствуют').get('id', 'Сведения об id отсутствуют')
        if bool(re.search('[a-zA-Z]', question)):
            send_message(chat_id, text=f'Добрый день! Изложите Ваш вопрос.')
        else:
            send_message(chat_id, text=f'Уважаемый {name}! Спасибо, что выбрали услуги нашего Центра! Ваш вопрос принят в работу. Специалист свяжется с Вами!')
        return {'Ok': True}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% block head %}
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta
      name="description"
      content="Банкротство юридических и физических лиц в Краснодаре и крае. Представительство в арбитражном процессе. Правовая помощь в конкурсном производстве"
    />
    <meta name="author" content="" />
    <meta name="robots" content="all" />
    <title>Банкротство в Краснодаре - "Центр правовой помощи"</title>
    <!-- Favicon-->
    <link
      rel="icon"
      type="image/x-icon"
      href="{{ url_for('static', filename='assets/femida_ejrr8cay6n91.ico') }}"
    />
    <link
      rel="icon"
      href="https://irina23.ru/favicon.ico"
      type="image/x-icon"
    />
    <!-- Bootstrap icons-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link
      href="{{ url_for('static', filename='css/styles.css') }}"
      rel="stylesheet"
    />
    <!--Canonical page-->
    <link rel="canonical" href="https://irina23.ru" />
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
      (function (m, e, t, r, i, k, a) {
        m[i] =
          m[i] ||
          function () {
            (m[i].a = m[i].a || []).push(arguments);
          };
        m[i].l = 1 * new Date();
        for (var j = 0; j < document.scripts.length; j++) {
          if (document.scripts[j].src === r) {
            return;
          }
        }
        (k = e.createElement(t)),
          (a = e.getElementsByTagName(t)[0]),
          (k.async = 1),
          (k.src = r),
          a.parentNode.insertBefore(k, a);
      })(
        window,
        document,
        "script",
        "https://mc.yandex.ru/metrika/tag.js",
        "ym"
      );
      ym(94130453, "init", {
        clickmap: true,
        trackLinks: true,
        accurateTrackBounce: true,
        webvisor: true,
      });
    </script>
    <noscript
      ><div>
        <img
          src="https://mc.yandex.ru/watch/94130453"
          style="position: absolute; left: -9999px"
          alt=""
        /></div
    ></noscript>
    <!-- /Yandex.Metrika counter -->
  </head>
  {% endblock %} {% block body %}
  <!-- Icons Grid-->
  <section class="features-icons bg-light text-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="bi-window m-auto text-primary"></i>
            </div>
            <h3>Процедура банкротства</h3>
            <p class="lead mb-0">
              Эффективное представительство по защите прав физических и
              юридических лиц. Сотрудники с опытом работы в системе
              арбитражных судов всех инстанций!
            </p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="bi-layers m-auto text-primary"></i>
            </div>
            <h3>Банкротство юридических лиц</h3>
            <p class="lead mb-0">
              Сопровождение процедуры банкротства на любой стадии!
            </p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="bi-terminal m-auto text-primary"></i>
            </div>
            <h3>Банкротство физических лиц</h3>
            <p class="lead mb-0">
              100% успешных кейсов по защите прав граждан. Законные и
              эффективные подходы по избавлению от долговой нагрузки!
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <footer class="footer bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
          <ul class="list-inline mb-2">
            <li class="list-inline-item"><a href="#!">О нас</a></li>
            <li class="list-inline-item">⋅</li>
            <li class="list-inline-item"><a href="#!">Контакты</a></li>
            <li class="list-inline-item">⋅</li>
            <li class="list-inline-item">
              <a href="#!">Условия и соглашения</a>
            </li>
            <li class="list-inline-item">⋅</li>
            <li class="list-inline-item">
              <a href="#!">Политика конфиденциальности</a>
            </li>
          </ul>
          <p class="text-muted small mb-4 mb-lg-0">
            &copy; Краснодар 2023. Правообладателем установлены ограничения.
          </p>
        </div>
        <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
          <ul class="list-inline mb-0">
            <li class="list-inline-item me-4">
              <a href="#!"><i class="bi-facebook fs-3"></i></a>
            </li>
            <li class="list-inline-item me-4">
              <a href="#!"><i class="bi-twitter fs-3"></i></a>
            </li>
            <li class="list-inline-item me-4">
              <a href="#!"><i class="bi-instagram fs-3"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Core theme JS-->
  <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
  <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
  <!-- * *                               SB Forms JS                               * *-->
  <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
  <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
  <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
  {% endblock %}
</html>

app/templates/claimform.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block head %} 
{{ super() }}

{% block navbar %}
<!-- Navigation-->
<nav class="navbar navbar-light bg-light static-top">
    <div class="container">
        <h1><a class="navbar-brand"></h1>            
        <ul class="list-inline mb-0">
            <li class="list-inline-item me-4">
                <a class="text-lg-end text-primary" style="margin-right: 30px; font-size: large;" href="{{ url_for('main.index') }}"><b>Вернуться на начальную страницу</b></a>
            </li>
        </ul>
    </div>
</nav>
{% endblock %}
{% block header %}
<header class="masthead">
    <div class="container position-relative">
        <div class="row justify-content-center">
            <div class="col-xl-6">
                <div class="text-center text-info">
                    <!-- Page heading-->
                    <h1 class="mb-5"><em>Центр правовой помощи при банкротстве</em></h1>
                <div class="text-center text-white">
                    <!-- Page heading-->
                    {% if not success %}
                    <h2 class="mb-5">Пожалуйста, заполните форму!</h2>
                    {% endif %}
                    <!-- Signup form-->
                    <!-- * * * * * * * * * * * * * * *-->
                    <!-- * * SB Forms Contact Form * *-->
                    <!-- * * * * * * * * * * * * * * *-->
                    <!-- This form is pre-integrated with SB Forms.-->
                    <!-- To make this form functional, sign up at-->
                    <!-- https://startbootstrap.com/solution/contact-forms-->
                    <!-- to get an API token!-->
                    
                    <!--Claim info input-->
                    <p class="text-center text-info" style="font-size: x-large;">{{ success }}</p>            
                    {% if success %}
                    <p><a class="text-center text-white" style="margin-bottom: 25px; font-size: x-large;" href="{{ url_for('main.claim_form') }}">Подать ещё одну заявку</a></p>
                    {% endif %}
                    {% if not success %}
                    <form action="" method="post">
                        {{ csrf_token }}
                        {{ form.hidden_tag() }}
                        {{ wtf.form_errors(form, hiddens="only") }}
                        <h4 class="text-center">Как к Вам обращаться?</h4>
                        {{ wtf.form_field(form.name, class="form-control form-control-lg") }}
                        {% if form.name.errors %}
                        <ul class="error" style="color:rgb(220, 20, 20)">
                            {% for error in form.name.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <h4 class="text-center" style="margin-top: 25px;">Ваш Email</h4>
                        {{ wtf.form_field(form.email, class="form-control form-control-lg") }}
                        {% if form.email.errors %}
                        <ul class="error" style="color:rgb(220, 20, 20)">
                            {% for error in form.email.errors %}                            
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <h4 class="text-center" style="margin-top: 25px;">Ваш номер телефона</h4>
                        {{ wtf.form_field(form.phone_number, class="form-control form-control-lg") }}
                        {% if form.phone_number.errors %}
                        <ul class="error" style="color:rgb(220, 20, 20)">
                            {% for error in form.phone_number.errors %}
                            {% set error = 'Неверный формат номера' %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <h4 class="text-center" style="margin-top: 25px;">Ваш населенный пункт</h4>
                        {{ wtf.form_field(form.location, class="form-control form-control-lg") }}   
                        <h4 class="text-center" style="margin-top: 25px;">Изложите Ваш вопрос</h4>
                        {{ wtf.form_field(form.fabula, class="form-control form-control-lg", style="min-height: 250px") }}
                        <div style="float: center; margin-top: 25px;"> 
                        {{ wtf.form_field(form.submit, button_map={'submit': 'btn btn-primary btn-lg'}) }}                        
                        </div> 
                    </form>
                    {% endif  %}
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% endblock %}

app/templates/index.html
{% extends 'base.html' %} {% import "bootstrap/wtf.html" as wtf %} {% block head
%} {{ super() }} {% block navbar %}
<!-- Navigation-->
<nav class="navbar navbar-brand bg-light static-top">
  <div class="container">
    <a class="btn btn-primary" href="{{ url_for('main.claim_form') }}"
      ><b>Оставить заявку на сайте</b></a
    >
    <ul class="list-inline mb-0">
      <li class="list-inline-item me-4">
        <a href="https://t.me/brain_iobot"><i class="bi-telegram fs-3"></i></a>
      </li>
      <a class="text-lg-end text-primary" href="https://t.me/brain_iobot"
        ><b>Telegram</b></a
      >
    </ul>
  </div>
</nav>
{% endblock %}
<!-- Masthead-->
{% block header %}
<header class="masthead">
  <!--<div><img src="{{ url_for('static', filename='assets/irina23_1.jpg') }}" style="position:absolute;" alt="irina23_1" width="384" height="330"></div>-->
  <div class="container position-relative">
    <div class="row justify-content-center">
      <div class="col-xl-6">
        <div class="text-center text-info">
          <!-- Page heading-->
          <h1 class="mb-5"><em>Центр правовой помощи при банкротстве</em></h1>
          {% if not success %} {% if not repeat %}
          <!--<h2 class="mb-5"><em>Добрый день! Изложите Ваш вопрос</em></h2>-->
          <div
            class="container position-relative text-white"
            style="
              position: absolute;
              font-family: 'Franklin Gothic Medium';
              font-size: x-large;
              text-align: left;
            "
          >
            <ul>
              <img
                style="margin-right: 10px"
                src="https://thumb.tildacdn.com/tild3961-3138-4435-b532-326564643432/-/resize/36x/-/format/webp/check-icon.png"
              />Ваши долги - наша забота!
            </ul>
            <ul>
              <img
                style="margin-right: 10px"
                src="https://thumb.tildacdn.com/tild3961-3138-4435-b532-326564643432/-/resize/36x/-/format/webp/check-icon.png"
              />Полное списание долгов без рисков!
            </ul>
            <ul>
              <img
                style="margin-right: 10px"
                src="https://thumb.tildacdn.com/tild3961-3138-4435-b532-326564643432/-/resize/36x/-/format/webp/check-icon.png"
              />Поможем сохранить имущество!
            </ul>
            <ul>
              <img
                style="margin-right: 10px"
                src="https://thumb.tildacdn.com/tild3961-3138-4435-b532-326564643432/-/resize/36x/-/format/webp/check-icon.png"
              />Вашим кейсом займется опытный юрист!
            </ul>
            <!-- Page heading-->
            <ul>
              <img
                style="margin-right: 10px"
                src="https://thumb.tildacdn.com/tild3961-3138-4435-b532-326564643432/-/resize/36x/-/format/webp/check-icon.png"
              />Оставьте Ваш email. С Вами свяжется специалист!
            </ul>
          </div>
          {% endif %} {% endif %}
          <h4 class="mb-5 text-white"><em>{{ success }}{{ repeat }}</em></h4>
          <!-- Signup form-->
          <!-- * * * * * * * * * * * * * * *-->
          <!-- * * SB Forms Contact Form * *-->
          <!-- * * * * * * * * * * * * * * *-->
          <!-- This form is pre-integrated with SB Forms.-->
          <!-- To make this form functional, sign up at-->
          <!-- https://startbootstrap.com/solution/contact-forms-->
          <!-- to get an API token!-->
          <form
            action="{{ url_for('main.get_email') }}"
            class="form-subscribe"
            id="contactForm"
            method="post"
          >
            <!-- Email address input-->
            <div class="row">
              <div class="col">
                <input
                  class="form-control form-control-lg"
                  id="emailAddress"
                  type="email"
                  pattern="^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$"
                  placeholder="Ваш Email адрес"
                  name="email"
                />
              </div>
              <div class="col-auto">
                <button
                  class="btn btn-primary btn-lg"
                  id="submitButton"
                  type="submit"
                >
                  <b>Отправить</b>
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %} {% endblock %}